// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdg3mUI0Mj84KoFVFyJTeLsBJQ3nWM0qE',
    appId: '1:141994525513:web:2792cd43958c2a7469d098',
    messagingSenderId: '141994525513',
    projectId: 'fir-auth-567fc',
    authDomain: 'fir-auth-567fc.firebaseapp.com',
    storageBucket: 'fir-auth-567fc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB04jfzbnA2oAJ7uDOT2j3BOAMnMBW6kl4',
    appId: '1:141994525513:android:d41f312b177d0b1369d098',
    messagingSenderId: '141994525513',
    projectId: 'fir-auth-567fc',
    storageBucket: 'fir-auth-567fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWZgANbSDLK5g27BmyRnvt1ohGszJgJVU',
    appId: '1:141994525513:ios:3bb41d820b6f715969d098',
    messagingSenderId: '141994525513',
    projectId: 'fir-auth-567fc',
    storageBucket: 'fir-auth-567fc.appspot.com',
    iosClientId: '141994525513-eh1s04l7dhadnpak48f3b7tdbnp31rvl.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDemo',
  );
}
