// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBG0CqxyLyJq88bVbCxRik7R8cOuc8tdM',
    appId: '1:930209986753:web:1a9c1905a038af78567c40',
    messagingSenderId: '930209986753',
    projectId: 'flutter-chat-app-2c330',
    authDomain: 'flutter-chat-app-2c330.firebaseapp.com',
    storageBucket: 'flutter-chat-app-2c330.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArXDkayuMYXJVnnkaH_d8LeQ6GqRMm3FE',
    appId: '1:930209986753:android:6af0cad949cd0960567c40',
    messagingSenderId: '930209986753',
    projectId: 'flutter-chat-app-2c330',
    storageBucket: 'flutter-chat-app-2c330.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUuDFAB9_aDj-o_AaBBOuVUFqGGm0MA6s',
    appId: '1:930209986753:ios:773eee6f3faae632567c40',
    messagingSenderId: '930209986753',
    projectId: 'flutter-chat-app-2c330',
    storageBucket: 'flutter-chat-app-2c330.appspot.com',
    iosClientId: '930209986753-e2bpbq27perbrufv6gpqmsc0enfdkibg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterDemo',
  );
}
